language: go
go:
  - 1.16.x
install:
  - go get GitHub.com/gohugoio/hugo
scipt:
  - mkdir -p themes/beautifulhugo && git clone https://Github.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo
deploy:
  provider: pages
  skip_cleanup: true
  GitHub_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
